create table job (id varchar(255) not null, job varchar(255), job_status varchar(255), start_date date, jobs varchar(255), primary key (id)) engine=InnoDB;
create table jobcalendar (id varchar(255) not null, user_id varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id varchar(255) not null, end_date date, start_date date, reservations varchar(255), primary key (id)) engine=InnoDB;
create table reservation_room (reservation_id varchar(255) not null, room_id varchar(255) not null) engine=InnoDB;
create table room (id varchar(255) not null, number_of_people integer not null, price_per_night integer not null, jobs_in_room varchar(255), primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, e_mail varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table user add constraint UK_5awx5dcb9xdv5m1bl38bmoke0 unique (e_mail);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table job add constraint FKprqafpkb0966dcqo1kunvocsh foreign key (jobs) references jobcalendar (id);
alter table jobcalendar add constraint FK8suy3ixttwg4kw7ad5jnsvty foreign key (user_id) references user (id);
alter table reservation add constraint FKqn5m90me49118dt3q0cglbw2l foreign key (reservations) references user (id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (id);
alter table room add constraint FKpgj5wa1406xskhis78x96eecg foreign key (jobs_in_room) references job (id);
create table job (id varchar(255) not null, job varchar(255), job_status varchar(255), start_date date, jobs varchar(255), primary key (id)) engine=InnoDB;
create table jobcalendar (id varchar(255) not null, user_id varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id varchar(255) not null, end_date date, start_date date, reservations varchar(255), primary key (id)) engine=InnoDB;
create table reservation_room (reservation_id varchar(255) not null, room_id varchar(255) not null) engine=InnoDB;
create table room (id varchar(255) not null, number_of_people integer not null, price_per_night integer not null, jobs_in_room varchar(255), primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, e_mail varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table user add constraint UK_5awx5dcb9xdv5m1bl38bmoke0 unique (e_mail);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table job add constraint FKprqafpkb0966dcqo1kunvocsh foreign key (jobs) references jobcalendar (id);
alter table jobcalendar add constraint FK8suy3ixttwg4kw7ad5jnsvty foreign key (user_id) references user (id);
alter table reservation add constraint FKqn5m90me49118dt3q0cglbw2l foreign key (reservations) references user (id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (id);
alter table room add constraint FKpgj5wa1406xskhis78x96eecg foreign key (jobs_in_room) references job (id);
create table job (id varchar(255) not null, job varchar(255), job_status varchar(255), start_date date, jobs varchar(255), primary key (id)) engine=InnoDB;
create table jobcalendar (id varchar(255) not null, user_id varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id varchar(255) not null, end_date date, start_date date, reservations varchar(255), primary key (id)) engine=InnoDB;
create table reservation_room (reservation_id varchar(255) not null, room_id varchar(255) not null) engine=InnoDB;
create table room (id varchar(255) not null, number_of_people integer not null, price_per_night integer not null, jobs_in_room varchar(255), primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, e_mail varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table user add constraint UK_5awx5dcb9xdv5m1bl38bmoke0 unique (e_mail);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table job add constraint FKprqafpkb0966dcqo1kunvocsh foreign key (jobs) references jobcalendar (id);
alter table jobcalendar add constraint FK8suy3ixttwg4kw7ad5jnsvty foreign key (user_id) references user (id);
alter table reservation add constraint FKqn5m90me49118dt3q0cglbw2l foreign key (reservations) references user (id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (id);
alter table room add constraint FKpgj5wa1406xskhis78x96eecg foreign key (jobs_in_room) references job (id);
create table job (id varchar(255) not null, job varchar(255), job_status varchar(255), start_date date, jobs varchar(255), primary key (id)) engine=InnoDB;
create table jobcalendar (id varchar(255) not null, user_id varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id varchar(255) not null, end_date date, start_date date, reservations varchar(255), primary key (id)) engine=InnoDB;
create table reservation_room (reservation_id varchar(255) not null, room_id varchar(255) not null) engine=InnoDB;
create table room (id varchar(255) not null, number_of_people integer not null, price_per_night integer not null, jobs_in_room varchar(255), primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, e_mail varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table user add constraint UK_5awx5dcb9xdv5m1bl38bmoke0 unique (e_mail);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table job add constraint FKprqafpkb0966dcqo1kunvocsh foreign key (jobs) references jobcalendar (id);
alter table jobcalendar add constraint FK8suy3ixttwg4kw7ad5jnsvty foreign key (user_id) references user (id);
alter table reservation add constraint FKqn5m90me49118dt3q0cglbw2l foreign key (reservations) references user (id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (id);
alter table room add constraint FKpgj5wa1406xskhis78x96eecg foreign key (jobs_in_room) references job (id);
create table job (id varchar(255) not null, job varchar(255), job_status varchar(255), start_date date, jobs varchar(255), primary key (id)) engine=InnoDB;
create table jobcalendar (id varchar(255) not null, user_id varchar(255), primary key (id)) engine=InnoDB;
create table reservation (id varchar(255) not null, end_date date, start_date date, reservations varchar(255), primary key (id)) engine=InnoDB;
create table reservation_room (reservation_id varchar(255) not null, room_id varchar(255) not null) engine=InnoDB;
create table room (id varchar(255) not null, number_of_people integer not null, price_per_night integer not null, jobs_in_room varchar(255), primary key (id)) engine=InnoDB;
create table user (id varchar(255) not null, e_mail varchar(255) not null, firstname varchar(255), lastname varchar(255), password varchar(255) not null, role varchar(255), username varchar(255) not null, primary key (id)) engine=InnoDB;
alter table user add constraint UK_5awx5dcb9xdv5m1bl38bmoke0 unique (e_mail);
alter table user add constraint UK_sb8bbouer5wak8vyiiy4pf2bx unique (username);
alter table job add constraint FKprqafpkb0966dcqo1kunvocsh foreign key (jobs) references jobcalendar (id);
alter table jobcalendar add constraint FK8suy3ixttwg4kw7ad5jnsvty foreign key (user_id) references user (id);
alter table reservation add constraint FKqn5m90me49118dt3q0cglbw2l foreign key (reservations) references user (id);
alter table reservation_room add constraint FKe368pj2d58a8xx37fk8p6k1jl foreign key (room_id) references room (id);
alter table reservation_room add constraint FK1p8c0gdgl9nnw8g3mavqchw2j foreign key (reservation_id) references reservation (id);
alter table room add constraint FKpgj5wa1406xskhis78x96eecg foreign key (jobs_in_room) references job (id);
